unique_ids:
  forms:
    Landing_page: SZB3D3C46IQP63TUEMBWIQIBXXLA4IJ5
  modules: {}
  server_modules: {}
  assets:
    EasyCook_logo.png: '1722571308508302177939521.8822'
    Landing_page_background.jpg: '1722572285998616870000353.6569'
    standard-page.html: 2HXOJ3K7DCA7LBIX33ZEHPJNSSW5BBVQ
    theme.css: JMDL6UM2CMF7UMX3MMKCZBSNHPYKA25L
  scripts: {}
